---
- name: Playbook
  hosts: ec2
  remote_user: ubuntu
  become: yes
  vars:
#path of the ssh key in local 
   ansible_ssh_private_key_file: "/mnt/c/Users/pozey/Downloads/terraformshrisab.pem"
  roles:
    - aws
    - clone_project
    - node
    - ip_replace
    - mysql
    